---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
ratings:
  paths:
  - "**.py"
exclude_paths:
  - tests/
  - docs/
  - build/
  - dist/
