repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-ast


  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [ -r, --in-place, --wrap-descriptions, '120', --wrap-summaries, '120', -- ]

  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-check-mock-methods
      - id: rst-directive-colons


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.3
    hooks:
      - id: pyupgrade
        args: [ --py36-plus ]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt

  # Notebook formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort==5.6.4 ]

      - id: nbqa-pyupgrade
        additional_dependencies: [ pyupgrade==2.7.4 ]
        args: [ --py37-plus ]

  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.48'
    hooks:
      - id: check-manifest
        stages: [ manual ]

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
