checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: '3.6.3'
    dependencies:
        # Runs before inferred commands
        before:
            - 'sudo apt-get install -y libyaml-dev'
            - 'pip install Cython'
            - 'pip install hypothesis'
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests: true
filter:
    excluded_paths:
        - '/tests/*'
    dependency_paths:
        - 'lib/*'
