
os:
  - linux
#  - osx
language: python
python:
 - '2.7'
 - '3.4'
 - '3.5'
 - '3.6'
matrix:
 include:
  - os: osx
    language: generic

#cache: pip

before_install:

- . ci/install_conda.sh

- . ci/setup_env.sh

install:
- pip install .

script:
- . ci/install_tester.sh

- . ci/run_tests.sh

- . ci/testbuild_docs.sh

after_success:
- coveralls



deploy:
  - provider: pypi
    user: phynix
    password:
      secure: "K4sQLzchDacZK5q/fMndLO+max2cMSA+a+TEk3HCl9+ALo99E8ywBEQJPzoSDwC8/7O3HZA884I16pDMpTjX7TBMgvOTGwCGWISdCPJXy7h7exer4VzwU24V48S8cPLBp5Gw/5aMUmDGW9d9btTxccKT0F312DRszyM+uLOPAvdAv9J5FucVXWy87CjdNp3/W1U8N4rzBtsFKbG5zOn/xU4DH/BxwovUs9n/Jl2YC7UxG7dUV4qeY0vucMyhrXRHM9bh4zLxXdtNKoCuPSrE/z5R4qMD588+o/1j5em1TASriynTWQnQLkunJ6J1cZkZ8HRjcFdgK9wRO7Dlf2KAIrhPtl/R1dZVFaeY+QLQQVNTsTHzPrZpp6c+mdPk8GfQhy+oUEQ+4rZMt44WD8AhLZO6aPuM0+0BxLus0qZ+AHUZnJHh0GlmsHoMLBBrx4hf+emCip5EF4lY7lThHNSlnxRXKKoZyUf2njJShzCHQtvm3+keit+N9TfCKhzABGzldjWYDrtSVBCyW5Hvwrm/QICMDXf2r38qcF6+Tiea6IyQjs9Zn38T3/BeJPTHHIpIYP2jKmlvtqkhc3XsXAcTx8YF0VnL4gjZAkoVmQ/KoRjxZGHkSDm04CinYPoDgGDumsKomyhgzxWF494Wp1+UOEI8gGcSFsiQOH2C8EpVVDo="
    distributions: sdist bdist_wheel
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME = "linux"

  - provider: pages
    skip_cleanup: true
    github_token:
      secure: "CqHGP/iah+GiUJVrScDTCbmSz+1CqQ7vdxS0o9PF7mfnGgnqfu38FKz6OA85vrI1XY0L6hE9SlPId4yH3EiG8y19XKMLd4EMAg3WlA0T9Z2hgafOSa0ZHkZi32yJfVzoPYspvRyXYZQ7ggRj6l3XGvsioY3023R5CPRPBGEVU38WHvl2Fskd+lDvwkBwVHSmy6kAxtPJe1z84oJhheHNtSuOtKlezdnndmU0wO2hX08wPegluuACe8ez08Qe8OB56X7sZCHoWvstZE6xdBkSjjnRb54Dm7Ll6313PHQHSXI0JBDDtKfRrqaI6J7ByieZA1SPNXtzsnq0/Hr47GvJ3Whcvc1tCaeEMt3q/JTCLcBOG0oRNZeJUiXObkX7PyHOCdUmLJ/brOeLHyTNnUFoHHr3IXFqLUqVnSjf/BoMeeW66Tfq/1BoyrInwpIoOJzN+aH0vjXXPFhUOUZq2dizMopSQ9IcG/etmrsF0LokqVaUS8nrJzS//n85UXa9U0EFpVd7VHzPwt9L8OZIAIe5SIBhkGyAMlcm059pmF7dPZL2rsfZ1JSZS6/lyXggI/cW+cYnJ8z7bDl2xqCkEAWlLJCyNTwJeoZe4NJxUM96yKyQSLilQxqDoIgvxYb9LN5qJ2WF4IFVVh0uRD9Wb+nEqVEc/pyXSRYR+jpjuj0T8I8="
    local_dir: docs/api/_build/html
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME = "linux"
