
os:
  - linux
#  - osx
language: python
python:
 - '2.7'
 - '3.4'
 - '3.5'
 - '3.6'
 - "3.7-dev"
# - "3.7"
matrix:
 include:
  - os: osx
    language: generic

#cache: pip

before_install:

- . ci/install_conda.sh

- . ci/setup_env.sh

install:
- pip install .

script:
- . ci/install_tester.sh

- . ci/run_tests.sh

- . ci/testbuild_docs.sh

after_success:
- coveralls



deploy:
  - provider: pypi
    user: phynix
    password:
      secure: "sYaUzRnBXwBLFUCK1Mq7gXcPqcQ91+pGiOvUT8WSsrusK+Td4qvpIDP/fRQTiUkd0x5xXv206smGGjim+JP9xAY2RVDVI+xfxQThxIEH4ne5rDJnq66AR40RW7205MiHOw4kMA39sSrIw4Gxl+H9UOEZBAPOMIFhDRXIdbuc/xBfHbD9J26xynlIqzY3hC+yfz4Aqz/4uSRWmifeYIYEqvy5nfaMNMs3mqqGbCKQ4Wi7QDX4L6Xr2T0VuqoAQs767ftbOFezPWGPJTPB37cNyT4/XgJWhMfiFFAIbqaP82l8qmZga0Bh5EzvaYA/9YcT4HXWUcp/teUbsZfiQKsIuRYPvW2nV43xLGvzwAZ3ur3cAzM4ZAK1NIeWUhfP93/miHiY9H6pyXPqsPVOpYloNbp//atushgrSccLxL12Q4UvorKaJ8DDZAd0uGgDb9zH5JIkfWhP5nxSVFLjeErKDTl5oSv4f81MMmjV2B6ZvI1MXHarOMpsAq7z/51HL+Okt3uoWBFKfVBxAYWHSgZR2p5ewCdzb3DFRsZV+shQu5nWQl01NSIfB56GSkgORpjYdHe8ekCDgUdOK8erLdyQXoHZxiWjHZpD8qTOJsTe0gapMxS5qjM9127HxYvOSh5+UxY8CVxPrEXqR3jKAQaDMOyklOnHZeeizgyWJgSsj4M="
    distributions: sdist bdist_wheel
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME = "linux"

  - provider: pages
    skip_cleanup: true
    github_token:
      secure: "CqHGP/iah+GiUJVrScDTCbmSz+1CqQ7vdxS0o9PF7mfnGgnqfu38FKz6OA85vrI1XY0L6hE9SlPId4yH3EiG8y19XKMLd4EMAg3WlA0T9Z2hgafOSa0ZHkZi32yJfVzoPYspvRyXYZQ7ggRj6l3XGvsioY3023R5CPRPBGEVU38WHvl2Fskd+lDvwkBwVHSmy6kAxtPJe1z84oJhheHNtSuOtKlezdnndmU0wO2hX08wPegluuACe8ez08Qe8OB56X7sZCHoWvstZE6xdBkSjjnRb54Dm7Ll6313PHQHSXI0JBDDtKfRrqaI6J7ByieZA1SPNXtzsnq0/Hr47GvJ3Whcvc1tCaeEMt3q/JTCLcBOG0oRNZeJUiXObkX7PyHOCdUmLJ/brOeLHyTNnUFoHHr3IXFqLUqVnSjf/BoMeeW66Tfq/1BoyrInwpIoOJzN+aH0vjXXPFhUOUZq2dizMopSQ9IcG/etmrsF0LokqVaUS8nrJzS//n85UXa9U0EFpVd7VHzPwt9L8OZIAIe5SIBhkGyAMlcm059pmF7dPZL2rsfZ1JSZS6/lyXggI/cW+cYnJ8z7bDl2xqCkEAWlLJCyNTwJeoZe4NJxUM96yKyQSLilQxqDoIgvxYb9LN5qJ2WF4IFVVh0uRD9Wb+nEqVEc/pyXSRYR+jpjuj0T8I8="
    local_dir: docs/api/_build/html
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME = "linux"
