name: tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 150
    strategy:
      max-parallel: 8
      fail-fast: False
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    name: tests on ubuntu with ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=in-tree-build .
          pip install cython
      - name: Test with pytest
        run: |
          . ci/install_tester.sh

          . ci/run_tests.sh
      - name: Build docs
        run: |
          . ci/testbuild_docs.sh
